### ISSUE TITLE
determine theme of app

### ISSUE THREAD

**Issue by Aurorathebadass** [AmaratheCapybara/PluralSocialMedia#30]
solar system theme yes or no?

**Comment by Aurorathebadass** [comment]
I say yes so Twitter and Facebook can't sue us. It's better to have some kind of theming than be close to mirroring them. even if it is just vaguely themed to the solar system space thing. Nick also said space theming would be better even if it is harder.  I think it will be easier to explain what is going on too. I will adjust everything to the theming soon.

**Comment by Aurorathebadass** [comment]
Color Themes are 
background: #050C1D
Accents/Buttons: #77B602
Notification/alert: #FF6F61
Text: #FFFF
Third and lively: #F4A261
Third and Calm: #B4D2FF

**Comment by Jaenatheseastar** [comment]
ooh that is nice of you. Thanks for putting the colors somewhere we can see. @Aurorathebadass
