### ISSUE TITLE
decide on the color scheme and basic icons for the design

### ISSUE THREAD

**Issue by AmaratheCapybara** [AmaratheCapybara/PluralSocialMedia#8]
we were discussing solar system themes or something like a twitter or facebook clone. Maybe getting some poling from the plural community which would be more liked.

**Comment by Aurorathebadass** [comment]
![SystemChatLogo](https://github.com/user-attachments/assets/51947225-b359-4f0e-b19d-63966229fbcf)
logo for application

**Comment by Hopetheheartmagicmusician** [comment]
in #30 @Aurorathebadass  said the colors were this https://github.com/AmaratheCapybara/PluralSocialMedia/issues/30#issuecomment-2418199314

**Comment by Hopetheheartmagicmusician** [comment]
> Color Themes are
> background: #050C1D
> Accents/Buttons: #77B602
> Notification/alert: #FF6F61
> Text: #FFFF
> Third and lively: #F4A261
> Third and Calm: #B4D2FF
- #30 @Aurorathebadass
